FROM node:20-slim

RUN apt-get update
RUN apt-get install -y wget gnupg
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update
RUN apt-get install -y google-chrome-stable libxss1 --no-install-recommends
RUN rm -rf /var/lib/apt/lists/*

WORKDIR /home/pptruser


RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser

RUN chown -R pptruser:pptruser /home/pptruser

COPY cubbybear.js /home/pptruser/cubbybear.js
COPY .puppeteerrc2.cjs /home/pptruser/.puppeteerrc2.cjs

RUN chown -R pptruser:pptruser /home/pptruser/cubbybear.js
RUN chown -R pptruser:pptruser /home/pptruser/.puppeteerrc2.cjs

USER pptruser



RUN npm init -y
RUN npm i puppeteer

RUN mkdir -p /home/pptruser/data
RUN chmod 777 /home/pptruser/data


CMD ["node", "./cubbybear.js"]
